<?php

/**
 * @file
 * Provides a Payway Net payment method for Drupal Commerce
 *
 */

module_load_include('inc', 'commerce_westpac_payway_net', 'commerce_westpac_payway_net.forms');
// module_load_include('inc', 'commerce_westpac_payway_net', 'commerce_westpac_payway_net.cruft');

/**
 * Implements hook_menu().
 */
function commerce_westpac_payway_net_menu() {
  $items['checkout/payway_net_notify'] = array(
    'title' => t('Callback handler'),
    'page callback' => 'commerce_westpac_payway_net_notify_handler',
    'callback arguments' => array(1, 4),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'file' => 'commerce_westpac_payway_net.pages.inc',
  );
  // PayWay is still pinging this URL, so here's a handler to stop it spamming the logs.
  $items['westpac-payway-net-server-response'] = $items['checkout/payway_net_notify'];
  return $items;
}

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_westpac_payway_net_commerce_payment_method_info() {
  $payment_methods = array();
  $payment_methods['commerce_westpac_payway_net'] = array(
    'title' => t('Pay by credit card via Westpac PayWay Net'),
    'short_title' => t('Pay by credit card via Westpac PayWay Net'),
    'display_title' => t('Pay by credit card via Westpac PayWay Net'),
    'description' => t('Pay by credit card via Westpac PayWay Net'),
    'active' => TRUE,
    'terminal' => FALSE,
    'offsite' => TRUE,
    //'offsite_autoredirect' => TRUE,
  );
  return $payment_methods;
}

/**
 * Payment method callback: settings form.
 */
function commerce_westpac_payway_net_settings_form($settings = NULL) {
  $form = array();
  $settings = (array)$settings + array(
  'commerce_westpac_payway_net_encryptionKey' => '',
  'commerce_westpac_payway_net_billerCode' => '',
  'commerce_westpac_payway_net_username' => '',
  'commerce_westpac_payway_net_password' => '',
  'commerce_westpac_payway_net_caCertsFile' => '',
  'commerce_westpac_payway_net_merchantId' => 'TEST',
  'commerce_westpac_payway_net_paypalEmail' => 'test@example.com',
  'commerce_westpac_payway_net_payWayBaseUrl' => 'https://www.payway.com.au/',
  );
  $form['commerce_westpac_payway_net_encryptionKey'] = array(
    '#type' => 'textfield',
    '#title' => t('Encryption Key'),
    '#size' => 80,
    '#description' => t('eg. 123456789'),
    '#default_value' => $settings['commerce_westpac_payway_net_encryptionKey'],
    '#required' => TRUE,
  );
  $form['commerce_westpac_payway_net_billerCode'] = array(
    '#type' => 'textfield',
    '#title' => t('Biller Code'),
    '#size' => 80,
    '#description' => t('eg. 123456'),
    '#default_value' => $settings['commerce_westpac_payway_net_billerCode'],
    '#required' => TRUE,
  );
  $form['commerce_westpac_payway_net_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#size' => 80,
    '#description' => t('eg. K12345'),
    '#default_value' => $settings['commerce_westpac_payway_net_username'],
    '#required' => TRUE,
  );
  $form['commerce_westpac_payway_net_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#size' => 80,
    '#description' => t('eg. abcdefghijk'),
    '#default_value' => $settings['commerce_westpac_payway_net_password'],
    '#required' => TRUE,
  );
  $form['commerce_westpac_payway_net_caCertsFile'] = array(
    '#type' => 'textfield',
    '#title' => t('Path to cacerts.crt file'),
    '#size' => 80,
    '#description' => t('eg. /home/username/dev/certs/cacerts.crt'),
    '#default_value' => $settings['commerce_westpac_payway_net_caCertsFile'],
    '#required' => TRUE,
  );
  $form['commerce_westpac_payway_net_merchantId'] = array(
    '#type' => 'textfield',
    '#title' => t('Merchant Id'),
    '#size' => 80,
    '#description' => t('eg. TEST'),
    '#default_value' => $settings['commerce_westpac_payway_net_merchantId'],
    '#required' => TRUE,
  );
  $form['commerce_westpac_payway_net_paypalEmail'] = array(
    '#type' => 'textfield',
    '#title' => t('Return link text'),
    '#size' => 80,
    '#description' => t('eg. test@example.com'),
    '#default_value' => $settings['commerce_westpac_payway_net_paypalEmail'],
    '#required' => TRUE,
  );
  $form['commerce_westpac_payway_net_payWayBaseUrl'] = array(
    '#type' => 'textfield',
    '#title' => t('Return link text'),
    '#size' => 80,
    '#description' => t('eg. https://www.payway.com.au/'),
    '#default_value' => $settings['commerce_westpac_payway_net_payWayBaseUrl'],
    '#required' => TRUE,
  );
  return $form;
}

